### ISSUE TITLE
check profile

### ISSUE THREAD

**Issue by SimonGreenhill** [lexibank/birchallchapacuran#4]
This has a profile -- does it look ok? (if so, we need to add segments)

**Comment by tresoldi** [comment]
From the source, it looks like those horizontal bars are artifacts, or at least they were removed for the appendix: https://pure.mpg.de/rest/items/item_2332314_2/component/file_2332313/content (see Wari', first column, entry BIG A, p. 4: "hwaraʔ").

I assume we can just remove the offending horizontal bars in the profile? If ok, I can do that.

**Comment by LinguList** [comment]
I think I made it, but there are a couple of items to be modified. Glad if you give it a quick look, @tresoldi .

**Comment by SimonGreenhill** [comment]
Great! I think those can be removed

**Comment by tresoldi** [comment]
I'll do it now, so we get moving with the profiles.
